#!/usr/bin/env bash

echo "installing and updating Waffine dependencies"
# Move to project root
cd ..

parentname="$(basename "$(pwd)")"
if [ $parentname != "Waffine" ] && [ $parentname != "waffine" ]; then
  echo "Attempted setup from wrong directory -- move to Waffine/bin!"
  exit 1
fi

# Dependencies contained in lib directory.
if [ ! -d 'lib' ]; then
  echo "lib directory not present, quitting"
  exit 1
fi
cd lib

# redownload winterval files
if [ -d 'Winterval' ]; then 
  rm -r 'Winterval'
fi
wget 'https://github.com/Willmo3/Winterval/raw/refs/heads/main/release/winterval-v0.0.2.tar.gz'
tar -xzf 'winterval-v0.0.2.tar.gz' && rm 'winterval-v0.0.2.tar.gz'

cd ..
